/**
 * Direct schema initialisation script.
 * Runs CREATE TABLE IF NOT EXISTS for all ProctorAI tables directly against Neon.
 * No drizzle-kit prompts — safe to run multiple times.
 *
 * Usage:  node scripts/init-db.mjs
 */
import pg from 'pg';
import { readFileSync } from 'fs';

const { Client } = pg;

// Read DATABASE_URL from root .env if not in environment
function loadEnv() {
  try {
    const env = readFileSync('.env', 'utf8');
    for (const line of env.split('\n')) {
      const match = line.match(/^([^#=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        const val = match[2].trim().replace(/^["']|["']$/g, '');
        if (!process.env[key]) process.env[key] = val;
      }
    }
  } catch {
    // .env not found — rely on environment variables already set
  }
}

loadEnv();

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error('❌  DATABASE_URL is not set. Add it to your .env or environment.');
  process.exit(1);
}

const sql = `
-- ─── ProctorAI Schema ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clerk_id      TEXT    NOT NULL UNIQUE,
  name          TEXT,
  email         TEXT    NOT NULL,
  role          TEXT,
  institution_name TEXT,
  subject_area  TEXT,
  traffic_source TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  updated_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exams (
  id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  instructor_clerk_id  TEXT    NOT NULL,
  title                TEXT    NOT NULL,
  description          TEXT,
  subject              TEXT,
  duration_minutes     INTEGER NOT NULL,
  status               TEXT    NOT NULL DEFAULT 'draft',
  grading_mode         TEXT    NOT NULL,
  ai_config            JSONB,
  exam_type            TEXT,
  created_at           TIMESTAMP NOT NULL DEFAULT now(),
  updated_at           TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS questions (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exam_id          INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  text             TEXT    NOT NULL,
  type             TEXT    NOT NULL,
  options          JSONB,
  correct_answer   TEXT,
  reference_solution TEXT,
  points           INTEGER NOT NULL DEFAULT 1,
  difficulty       TEXT,
  "order"          INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  updated_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exam_sessions (
  id                INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exam_id           INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  student_clerk_id  TEXT    NOT NULL,
  student_email     TEXT,
  student_name      TEXT,
  access_code       TEXT    NOT NULL UNIQUE,
  status            TEXT    NOT NULL DEFAULT 'not_started',
  started_at        TIMESTAMP,
  completed_at      TIMESTAMP,
  submitted_at      TIMESTAMP,
  answers           JSONB,
  score             INTEGER,
  max_score         INTEGER,
  created_at        TIMESTAMP NOT NULL DEFAULT now(),
  updated_at        TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cheating_flags (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id  INTEGER NOT NULL REFERENCES exam_sessions(id) ON DELETE CASCADE,
  type        TEXT    NOT NULL,
  description TEXT,
  timestamp   TIMESTAMP NOT NULL DEFAULT now(),
  reviewed    BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS waitlist (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email      TEXT    NOT NULL UNIQUE,
  role       TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
`;

async function main() {
  const client = new Client({ connectionString: DATABASE_URL });
  await client.connect();
  console.log('✅  Connected to Neon database.');
  try {
    await client.query(sql);
    console.log('✅  All ProctorAI tables created (or already exist).');
    console.log('');
    console.log('Tables ready:');
    console.log('  • users');
    console.log('  • exams');
    console.log('  • questions');
    console.log('  • exam_sessions');
    console.log('  • cheating_flags');
    console.log('  • waitlist');
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error('❌  Migration failed:', err.message);
  process.exit(1);
});
