import pg from 'pg';
const { Client } = pg;

const DATABASE_URL = 'postgres://neondb_owner:npg_uitam2Spqb9T@ep-divine-glade-adt3sbj8-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require';

const sql = `
-- Drop existing tables to ensure a clean schema sync
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS cheating_flags CASCADE;
DROP TABLE IF EXISTS exam_sessions CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS waitlist CASCADE;

-- Create tables in dependency order
CREATE TABLE users (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clerk_id      TEXT    NOT NULL UNIQUE,
  name          TEXT,
  email         TEXT    NOT NULL,
  role          TEXT,
  institution_name TEXT,
  subject_area  TEXT,
  traffic_source TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  updated_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE exams (
  id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  instructor_clerk_id  TEXT    NOT NULL,
  title                TEXT    NOT NULL,
  description          TEXT,
  subject              TEXT,
  duration_minutes     INTEGER NOT NULL,
  status               TEXT    NOT NULL DEFAULT 'draft',
  grading_mode         TEXT    NOT NULL,
  ai_config            JSONB,
  exam_type            TEXT,
  access_code          TEXT    UNIQUE,
  created_at           TIMESTAMP NOT NULL DEFAULT now(),
  updated_at           TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE questions (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exam_id          INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  text             TEXT    NOT NULL,
  type             TEXT    NOT NULL,
  options          JSONB,
  correct_answer   TEXT,
  reference_solution TEXT,
  points           INTEGER NOT NULL DEFAULT 1,
  difficulty       TEXT,
  "order"          INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  updated_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE exam_sessions (
  id                INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exam_id           INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  student_clerk_id  TEXT    NOT NULL,
  student_email     TEXT,
  student_name      TEXT,
  access_code       TEXT    NOT NULL,
  status            TEXT    NOT NULL DEFAULT 'not_started',
  started_at        TIMESTAMP,
  completed_at      TIMESTAMP,
  submitted_at      TIMESTAMP,
  answers           JSONB,
  score             INTEGER,
  max_score         INTEGER,
  created_at        TIMESTAMP NOT NULL DEFAULT now(),
  updated_at        TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE answers (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id    INTEGER NOT NULL REFERENCES exam_sessions(id) ON DELETE CASCADE,
  question_id   INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  answer        TEXT    NOT NULL,
  attachments   JSONB,
  is_correct    INTEGER NOT NULL DEFAULT 0,
  points        INTEGER NOT NULL DEFAULT 0,
  feedback      TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE cheating_flags (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id    INTEGER NOT NULL REFERENCES exam_sessions(id) ON DELETE CASCADE,
  type          TEXT    NOT NULL,
  description   TEXT,
  clip_data     TEXT,
  detected_at   TIMESTAMP NOT NULL DEFAULT now(),
  review_status TEXT NOT NULL DEFAULT 'pending',
  reviewed_at   TIMESTAMP,
  review_note   TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE waitlist (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email      TEXT    NOT NULL UNIQUE,
  role       TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
`;

async function main() {
  const client = new Client({ connectionString: DATABASE_URL });
  await client.connect();
  console.log('Connected to Neon database.');
  try {
    await client.query(sql);
    console.log('Successfully dropped old tables and created brand new tables matching the correct schema.');
  } finally {
    await client.end();
  }
}

main().catch(err => {
  console.error('Recreation failed:', err.message);
  process.exit(1);
});
